branch-defaults:
  eb-config:
    environment: praisebooky-live
  master:
    environment: null
    group_suffix: null
environment-defaults:
  praisebooky-live:
    branch: null
    repository: null
global:
  application_name: praisebooky
  branch: null
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Puma with Ruby 2.5
    running on 64bit Amazon Linux/2.8.1
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
