default: &default
  auth0_client_id: <%= ENV['AUTH0_CLIENT_ID'] %>
  auth0_client_secret: <%= ENV['AUTH0_CLIENT_SECRET'] %>
  auth0_domain: <%= ENV['AUTH0_DOMAIN'] %>

development:
  <<: *default

test:
  <<: *default

production:
  secret_key_base: <%= ENV["1df08c000778d5604201f8403353c6c677822528d095ab41a99b739dbd1d966e457fe1a36effbf19ed6fe1527bb2f175ff67be30ca1260c9074b6a1292607565"] %>

