default: &default
  project_id: praisebooky_id
  #gcs_bucket: [YOUR_BUCKET_NAME]
  oauth2:
    client_id: 525808177862-661icl3q2jigqoketbgnhg8n9ds141r4.apps.googleusercontent.com
    client_secret: 0ZB_MfBTPQPMped77U7d8zvP

development:
  <<: *default

production:
  <<: *default